# Recurring jobs configuration
# See: https://github.com/rails/solid_queue#recurring-tasks

production:
  update_invoice_status:
    class: UpdateInvoiceStatusToOverdueJob
    schedule: every day at midnight
  weekly_reminder:
    class: WeeklyReminderToUserJob
    schedule: every Monday at 2:30pm Asia/Kolkata
  update_exchange_rates:
    class: UpdateExchangeRatesJob
    schedule: every day at 1am America/New_York
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

development:
  update_invoice_status:
    class: UpdateInvoiceStatusToOverdueJob
    schedule: every day at midnight
  weekly_reminder:
    class: WeeklyReminderToUserJob
    schedule: every Monday at 2:30pm Asia/Kolkata
  update_exchange_rates:
    class: UpdateExchangeRatesJob
    schedule: every day at 1am America/New_York
