development:
  :concurrency: 1
production:
  :concurrency: 1
:queues:
  - default
  - mailers
  - action_mailbox_routing
  - action_mailbox_incineration
  - active_storage_analysis
  - active_storage_purge
:schedule:
  weekly_reminder:
    cron: '0 14 * * * 1 Asia/Kolkata'   # Runs every monday at  14:00
    class: WeeklyReminderToUserJob
